spin_manifest_version = 2

[application]
name = "engineertools"
version = "0.1.0"
authors = ["Nico Bos <nico@bos.codes>"]
description = ""

[[trigger.http]]
route = "/..."
component = "engineertools"

[component.engineertools]
source = "target/wasm32-wasip1/release/engineertools.wasm"
allowed_outbound_hosts = []
[component.engineertools.build]
command = "cargo leptos build --release && LEPTOS_OUTPUT_NAME=engineertools cargo build --lib --target wasm32-wasip1 --release --no-default-features --features ssr"
watch = ["src/**/*.rs", "Cargo.toml", "style/main.scss", "style/**/*.scss"]

[[trigger.http]]
route = "/pkg/..."
component = "engineertools-pkg"

[component.engineertools-pkg]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "target/site/pkg", destination = "/" }]
